default_language_version:
  python: python3.8

default_stages: [ commit, push ]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black --config pyproject.toml
      types: [ python ]
      language: system
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.38.0
  hooks:
  - id: commitizen
    stages: [commit-msg]
