github_url = "https://github.com/{{ cookiecutter.github_user }}/{{ cookiecutter.project_name }}/"


[version]
current = "{{ cookiecutter.version }}"
# MAJOR.MINOR.PATCH (e.g. 0.1.0)
regex = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'


[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"


[[file]]
src = "setup.py"
{%- if cookiecutter.setup_py_uses_setuptools_scm == 'y' %}
search = "'fallback_version': '{current_version}'"
{%- else %}
search = "version='{current_version}'"
{%- endif %}


[[file]]
src = "README.rst"
search = "/v{current_version}.svg"


[[file]]
src = "README.rst"
search = "/v{current_version}...{{ cookiecutter.repo_main_branch }}"


[[file]]
src = "docs/conf.py"
search = "version = release = '{current_version}'"


[[file]]
src = "src/{{ cookiecutter.package_name }}/__init__.py"
search = "__version__ = '{current_version}'"


[[before_commit]]
name = "check changelog"
cmd = "grep -q {new_version} CHANGELOG.rst"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"