name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: cd website && yarn install && yarn build
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: ingwersen-erik
          git-password: ${{ secrets.GH_PAGES_DEPLOY }}
          deployment-branch: documentation
