name: documentation

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: ingwersen-erik
          git-password: ${{ secrets.GH_PAGES_DEPLOY }}
          deployment-branch: documentation
